### PR TITLE
Added uint and PROGMEM grammar

### PR DESCRIPTION
**Pull request by fega**
the PROGMEM reference is here https://www.arduino.cc/en/Reference/PROGMEM, 
Also I added the uint variables that are valid to the compiler

### CODE REVIEW

**Comment by szechyjs** [comment]
`uint_8`, `uint_16`, `uint_32`are already part of the `source.c` grammar.

Perhaps your current theme does not have `.type` defined. (atom/one-light-syntax#10)

**Comment by szechyjs** [comment]
Add `PROGMEM` to `storage.modifier.arduino`

**Comment by fega** [comment]
What about the uinX_t variables? should be deleted?

**Comment by szechyjs** [comment]
Yes, the `uinX_t` should be removed. They are handled by `source.c` which is included in this grammar.

**Pull request merged**
