### PR TITLE
Added functions an some constants

### PR DESCRIPTION
**Pull request by fega**
I revised the native Arduino.h library and decided to add DEG_TO_RAD and RAD_TO_DEG to avoid compiling problems

### CODE REVIEW

**Comment by szechyjs** [comment]
Only include arduino specific functions. All of those `math.h` functions are part of libc.

https://github.com/atom/language-c/blob/master/grammars/c.cson#L488-L511

**Comment by szechyjs** [comment]
Forgot about `floor`, also `sizeof` is a c operator.

Also change `entity.name.function.arduino` to `support.function.arduino`.

**Comment by fega** [comment]
@szechyjs Did you check the update?

**Comment by fega** [comment]
Hello @szechyjs, did you mean `B[01]{1,8}` or `\bB[01]{1,8}\b`? I ignore a lot of things about regex

**Comment by szechyjs** [comment]
@fega, yes the full regex would then be `'\bB[01]{1,8}\b'`

**Comment by fega** [comment]
Done xD

**Pull request merged**
